language: go
go:
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
script:
    - go test -v ./chapter1
    - $HOME/gopath/bin/goveralls -service=travis-ci
